# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Documents/CS251/branches/raymoneo/Assignment5-3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Documents/CS251/branches/raymoneo/Assignment5-3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/CS251/branches/raymoneo/Assignment5-3/CMakeFiles /home/student/Documents/CS251/branches/raymoneo/Assignment5-3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/CS251/branches/raymoneo/Assignment5-3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assignment5-3

# Build rule for target.
assignment5-3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assignment5-3
.PHONY : assignment5-3

# fast build rule for target.
assignment5-3/fast:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/build
.PHONY : assignment5-3/fast

AggregateStrategy.o: AggregateStrategy.cpp.o
.PHONY : AggregateStrategy.o

# target to build an object file
AggregateStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/AggregateStrategy.cpp.o
.PHONY : AggregateStrategy.cpp.o

AggregateStrategy.i: AggregateStrategy.cpp.i
.PHONY : AggregateStrategy.i

# target to preprocess a source file
AggregateStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/AggregateStrategy.cpp.i
.PHONY : AggregateStrategy.cpp.i

AggregateStrategy.s: AggregateStrategy.cpp.s
.PHONY : AggregateStrategy.s

# target to generate assembly for a file
AggregateStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/AggregateStrategy.cpp.s
.PHONY : AggregateStrategy.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Object.cpp.s
.PHONY : Object.cpp.s

Universe.o: Universe.cpp.o
.PHONY : Universe.o

# target to build an object file
Universe.cpp.o:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Universe.cpp.o
.PHONY : Universe.cpp.o

Universe.i: Universe.cpp.i
.PHONY : Universe.i

# target to preprocess a source file
Universe.cpp.i:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Universe.cpp.i
.PHONY : Universe.cpp.i

Universe.s: Universe.cpp.s
.PHONY : Universe.s

# target to generate assembly for a file
Universe.cpp.s:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Universe.cpp.s
.PHONY : Universe.cpp.s

Visitor.o: Visitor.cpp.o
.PHONY : Visitor.o

# target to build an object file
Visitor.cpp.o:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Visitor.cpp.o
.PHONY : Visitor.cpp.o

Visitor.i: Visitor.cpp.i
.PHONY : Visitor.i

# target to preprocess a source file
Visitor.cpp.i:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Visitor.cpp.i
.PHONY : Visitor.cpp.i

Visitor.s: Visitor.cpp.s
.PHONY : Visitor.s

# target to generate assembly for a file
Visitor.cpp.s:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/Visitor.cpp.s
.PHONY : Visitor.cpp.s

driverUgrad.o: driverUgrad.cpp.o
.PHONY : driverUgrad.o

# target to build an object file
driverUgrad.cpp.o:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/driverUgrad.cpp.o
.PHONY : driverUgrad.cpp.o

driverUgrad.i: driverUgrad.cpp.i
.PHONY : driverUgrad.i

# target to preprocess a source file
driverUgrad.cpp.i:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/driverUgrad.cpp.i
.PHONY : driverUgrad.cpp.i

driverUgrad.s: driverUgrad.cpp.s
.PHONY : driverUgrad.s

# target to generate assembly for a file
driverUgrad.cpp.s:
	$(MAKE) -f CMakeFiles/assignment5-3.dir/build.make CMakeFiles/assignment5-3.dir/driverUgrad.cpp.s
.PHONY : driverUgrad.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... assignment5-3"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AggregateStrategy.o"
	@echo "... AggregateStrategy.i"
	@echo "... AggregateStrategy.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Universe.o"
	@echo "... Universe.i"
	@echo "... Universe.s"
	@echo "... Visitor.o"
	@echo "... Visitor.i"
	@echo "... Visitor.s"
	@echo "... driverUgrad.o"
	@echo "... driverUgrad.i"
	@echo "... driverUgrad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

